version: '3.7'


services:

  task-php:
    container_name: task_php
    build:
      context: Docker/php
      dockerfile: Dockerfile
    volumes:
      - "./app:/app"

  task-nginx:
    container_name: task_nginx
    build:
      context: Docker/nginx
      dockerfile: Dockerfile
    volumes:
      - "./app:/app"
      - "./Docker/nginx/conf.d:/etc/nginx/conf.d"
    ports:
      - "8085:80"

  task-rabbit:
    container_name: task_rabbit
    image: rabbitmq:3.11.1-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./data/rabbit:/var/lib/rabbitmq"
    hostname: rabbit
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: 1234
      RABBITMQ_DEFAULT_VHOST: task-rabbit


